### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by matt-the-wizard** [matt-the-wizard/twin-taps#2]
As an admin user, I want to secure certain admin related pages, so that certain users can perform administrative tasks through the web interface.

- [x] When an unauthenticated user requests a protected server route, then it should respond with the login page.
- [x] When an unauthenticated user browsers to a protected client-side route, then it should display the login page and not the protected route.
- [x] When viewing the login page, I am able to enter my username and password.
- [x] Given I have not entered a value for username (or password), when I enter a value and then delete it, then I get a visual indication that the field is invalid
- [x] Given I have an invalid field, then I cannot send a request to login.
- [x] Given the login page, when submitting an invalid username/password combination, then the login page is displayed with an error message that does not reveal which (username or password) was incorrect: e.g. "Invalid username or password".
- [x] Given I have submitted valid credentials, when I view a protected server or client route, then I am able to view the route's page.
- [x] Given I have requested a protected route, when I log in with valid username/password credentials, then I am redirected to the protected page.
- [x] Given a valid username/password combination, when logging into the site, then the user is able to access protected pages.
- [x] proper test coverage of new files/features

**Comment by andrew-codes** [comment]
I'm not sure/convinced this is how this would or should work. What is the goal of the feature (versus how to accomplish it)? That will provide some insight into the discussion. Is the goal of this to allow users to login? In which case we may be able to break that down ever further.

**Comment by matt-the-wizard** [comment]
Yeah, I kind of grouped in two things here. One is for users to login, which uses the jwt token after being authorized. 

The other is setting up an API token so requests are only responded to if they come from the web client. 

We could break this down further, I already setup the jwt on the service so bullet 2 and 4 are already done.

**Comment by matt-the-wizard** [comment]
Ok I updated this issue to solely focus on Authorization, I am moving the API Token piece to another issue.

**Comment by andrew-codes** [comment]
The authentication of a user and the associated JWT token/session happens on the web server; not the API service. The token part is complete already, but verifying a provided username/password is valid (hitting the db from the web server) is not. I'm unsure what ports the db container exposes as of now, but will look into it. I am also unsure of the db's table structure to even know what table to query against; though I have only done a cursory glance.

**Comment by andrew-codes** [comment]
I changed the description to be less implementation specific and instead encompass the objective of the issue. There may/may not be a better way to implement it, but understanding the objective will help us stay focused and arrive at a good solution; as opposed to simply listing a solution. In other words, what is the problem we are solving versus here is a solution to some unknown problem.
