### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by andrew-codes** [matt-the-wizard/twin-taps#6]
As an admin user of Twin Taps, I want to be able to register another admin user, so that I can enable other users to interact with protected pages.

- [ ] When viewing a public page, then I can see a link for new user registration.
- [ ] When clicking the sign up link, then it takes me to a new user registration page.
- [ ] When registering as a new user, then I am prompted to enter my name, email, and password.
- [ ] Given I have not entered all fields, when submitting the registration form, then it notifies me that the missing fields are required
- [ ] Given I have entered a field, when deleting completely deleting the field's value, then it immediately shows an error message indicating the field is required
- [ ] When viewing the registration page, then there is a visual indication that all fields are required.
- [ ] Given I have entered valid input into all fields, when signing-up, then I can successfully sign-up.
- [ ] Given I have successfully signed-up, when logging in with my new user credentials, then I can successfully login.

**Comment by andrew-codes** [comment]
@matt-the-wizard Do we want to allow users to sign-up with Facebook or Google? Those should be separate issues, but this made me think of it. Seems it could be valuable.

**Comment by matt-the-wizard** [comment]
I think google might be a valid use case, but not sure about facebook. I will have to touch base with Nathan on that. I slightly modified the description of this issue to focus on other admin users being created, instead of public users.

**Comment by matt-the-wizard** [comment]
I wonder if we are introducing the concept of a root admin user, who manages what other admin users can do. The requirements I have been given so far, is the ability to grant other users registration to use protected pages, so I think this is fine for now.

**Comment by andrew-codes** [comment]
Yeh if there are no public users, then registration seems like an unneeded feature. I would imagine only another admin could add a user to the system.
